---

# Note: This isn't sufficient to run kanidm - you need
# to configure it (including running commands to create
# certificates & reset the admin + idm_admin passwords).

# Additionally you'll need to write /opt/p2-network/kanidm/data/server.toml
# see templates/kanidm/server.toml for an example.

- name: Create a directory for kanidm
  ansible.builtin.file:
    path: /opt/p2-network/kanidm
    state: directory

- name: Create a directory for kanidm/data
  ansible.builtin.file:
    path: /opt/p2-network/kanidm/data
    state: directory

- name: Write kanidm/docker-compose.yml
  ansible.builtin.template:
    src: templates/kanidm/docker-compose.yml
    dest: /opt/p2-network/kanidm/docker-compose.yml

- name: Create and start kanidm
  community.docker.docker_compose_v2:
    project_src: /opt/p2-network/kanidm/
  register: output
