version: "3.3"

services:
  traefik:
    image: "traefik:v2.11.2"
    restart: unless-stopped
    container_name: "traefik"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-tailscale.rule=Host(`traefik.quincy.thepatrick.cloud`) && ClientIP(`100.0.0.0/8`, `fd7a:115c:a1e0:ab12::/64`)"
      - "traefik.http.routers.api-tailscale.entrypoints=websecure"
      - "traefik.http.routers.api-tailscale.service=api@internal"
      - "traefik.http.routers.api-tailscale.tls=true"
      - "traefik.http.routers.api-tailscale.tls.certresolver=route53"
      - "traefik.http.routers.api-tailscale.tls.domains[0].main=*.quincy.thepatrick.cloud"
      - "per-container-role=arn:aws:iam::749916541518:role/anywhere/unicorn/quincy/quincy-traefik20240526073635461300000001"
    command:
      #- "--log.level=DEBUG"
      - "--api"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik_default"

      - "--providers.file.directory=/etc/traefik/"
      - "--providers.file.watch=true"

      - "--entrypoints.web.address=:80"
      # - "--entryPoints.web.forwardedHeaders.trustedIPs=172.19.0.0/16"
      - "--entrypoints.websecure.address=:443"
      # - "--entryPoints.websecure.forwardedHeaders.trustedIPs=172.19.0.0/16"

      - "--certificatesresolvers.route53.acme.storage=/etc/traefik-acme/route53.json"
      - "--certificatesresolvers.route53.acme.dnschallenge.provider=route53"
      - "--certificatesresolvers.route53.acme.dnschallenge.delaybeforecheck=0"

      - "--experimental.plugins.real-ip.moduleName=github.com/Paxxs/traefik-get-real-ip"
      - "--experimental.plugins.real-ip.version=v1.0.2"
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - ./traefik/:/etc/traefik/
      - ./acme/:/etc/traefik-acme/
      # - "/opt/p2-network/run/DOCKER_TRAEFIK_AWS_SHARED_CREDENTIALS_FILE:/etc/traefik-aws-credentials"
    environment:
      - TZ=Australia/Melbourne
      - AWS_REGION=ap-southeast-2
      - AWS_EC2_METADATA_SERVICE_ENDPOINT=http://{{ per_docker_roles_network.network.IPAM.Config[0].Gateway }}:9912/
      - TRAEFIK_CERTIFICATESRESOLVERS_route53_ACME_EMAIL_FILE=/run/secrets/acme_email
    secrets:
      - acme_email
    networks:
      - default
      - per_docker_roles

networks:
  per_docker_roles:
    name: {{ per_docker_roles_network.network.Name }}
    external: true

secrets:
  acme_email:
    file: /opt/p2-network/traefik/acme_email