---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - config.yml

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes
