---
- hosts: all
  become: true
  gather_facts: true

  vars_files:
    - config.yml

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: yes

    - name: Create a test direcotry
      ansible.builtin.file:
        path: /opt/p2-network/test/
        state: directory

    - name: Configure AWS IAM Roles Anywhere service
      include_tasks: tasks/aws-iam-roles-anywhere.yml

    - name: Configure Per Docker Roles service
      include_tasks: tasks/per-docker-roles.yml

    - name: Deploy Traefik
      include_tasks: tasks/traefik.yml
