name: deploy-project

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: quincy
    if: github.event_name != 'pull_request'
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_CI_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_CI_CLIENT_SECRET }}
          tags: tag:ci

      - name: starting SSH agent
        shell: bash
        run: |
          mkdir -p ~/.ssh
          eval $(ssh-agent)

      - name: Adding known host
        shell: bash
        run: |
          ssh-keyscan -p 22 "teagan.tuatara-puffin.ts.net" >> ~/.ssh/known_hosts

      - name: Inject netaddr into ansible-core
        run: |
          pipx inject ansible-core netaddr

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: main.yml
          directory: ./ansible
          requirements: requirements.yml
          vault_password: ${{secrets.VAULT_PASSWORD_QUINCY}}
          options: |
            --limit github
